#!/usr/bin/env bash
# Install nginx on remote web-01 server

apt-get update
apt-get upgrade
apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html;
}" > /etc/nginx/sites-available/default
service nginx restart