#!/usr/bin/env bash
# Displaying numbers with a specific pattern. 
i=1
for i in {1..100}; 
do
	i=$((i++))
	if (( i % 15 == 0 )); then
		echo "Fizzbuzz"
	elif (( i % 3 == 0 )); then 
		echo "Fizz"
	elif (( i % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$i"
fi
done
