#!/usr/bin/env bash
# Print "bad luck" for 4th loop, "good luck" for 8th loop
i=0
while [ $i -le 9 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
((i++))
done
