#!/usr/bin/env bash
# Printing bad luck from certain numbers, using counter.
i=0
while [ $i -le 19 ]
do
COUNTER=0
case $COUNTER in
	"4")
		echo "bad luck from China";;
	"9")
		echo "bad luck from Japan";;
	"17")
		echo "bad luck from Italy";;
	*)
		echo "";;
esac
((i++))
done
