#!/usr/bin/env bash
# Printing different information based on content of file.
school="school"

if [ -e $school ]; then
	echo "$school file exists"
	if [ -s $school ]; then
		echo "$school file is not empty"
	else
		echo "$school file is empty"
	fi
	if [ -f $school ]; then
		echo "$school is a regular file"
	else
		echo ""
	fi
else 
	echo "$school does not exist"
fi
