#!/usr/bin/env bash
# Printing different information based on content of file.
SCHOOL="school"
if [ -e $SCHOOL ]; then
	echo "school file exists"
else
	echo "school file does not exist"
fi
if [ -s $SCHOOL ]; then
	echo "school file is empty"	
else
	echo "school file is not empty"
fi

if [ -f $SCHOOL ]; then
	echo "school is a regular file"
else
	echo ""
fi
