#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server


config_frontend="\nfrontend main\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n"
config_backend="\nbackend web_servers\n\tbalance roundrobin\n\toption forwardfor\n\tserver 5568-web-01 35.181.8.93:80 check\n\tserver 5568-web-02 13.38.0.119:80 check\n"

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo ENABLED=1 | sudo tee -a /etc/default/haproxy
echo -e "$config_frontend""$config_backend" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start